[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[build.environment]
  NODE_VERSION = "18"
